name: XeraTablist
version: 1.2.0
main: Xera.Tablist.XeraTablist
authors: [Nate Legault, Pistonmaster]
description: Most advanced tablist plugin for anarchy servers out there!
softdepend: [PlaceholderAPI]
folia-supported: true
commands:
  tabrconfig:
    description: Reload the config
    permission: xera.tablist.reload
    usage: /tabrconfig
permissions:
  xera.tablist.reload:
    description: Permission to reload XeraTablist.